//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.07 at 09:26:43 PM EDT 
//


package model.com.rallydev.webservice.v1_34.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BuildDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BuildDefinition">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rallydev.com/webservice/v1_34/domain}WorkspaceDomainObject">
 *       &lt;sequence>
 *         &lt;element name="Builds" type="{http://rallydev.com/webservice/v1_34/domain}BuildDefinitionBuildsType" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LastBuild" type="{http://rallydev.com/webservice/v1_34/domain}Build" minOccurs="0"/>
 *         &lt;element name="LastStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Project" type="{http://rallydev.com/webservice/v1_34/domain}Project" minOccurs="0"/>
 *         &lt;element name="Projects" type="{http://rallydev.com/webservice/v1_34/domain}BuildDefinitionProjectsType" minOccurs="0"/>
 *         &lt;element name="Uri" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BuildDefinition", propOrder = {
    "builds",
    "description",
    "lastBuild",
    "lastStatus",
    "name",
    "project",
    "projects",
    "uri"
})
public class BuildDefinition
    extends WorkspaceDomainObject
{

    @XmlElement(name = "Builds")
    protected BuildDefinitionBuildsType builds;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "LastBuild")
    protected Build lastBuild;
    @XmlElement(name = "LastStatus")
    protected String lastStatus;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "Project")
    protected Project project;
    @XmlElement(name = "Projects")
    protected BuildDefinitionProjectsType projects;
    @XmlElement(name = "Uri")
    protected String uri;

    /**
     * Gets the value of the builds property.
     * 
     * @return
     *     possible object is
     *     {@link BuildDefinitionBuildsType }
     *     
     */
    public BuildDefinitionBuildsType getBuilds() {
        return builds;
    }

    /**
     * Sets the value of the builds property.
     * 
     * @param value
     *     allowed object is
     *     {@link BuildDefinitionBuildsType }
     *     
     */
    public void setBuilds(BuildDefinitionBuildsType value) {
        this.builds = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the lastBuild property.
     * 
     * @return
     *     possible object is
     *     {@link Build }
     *     
     */
    public Build getLastBuild() {
        return lastBuild;
    }

    /**
     * Sets the value of the lastBuild property.
     * 
     * @param value
     *     allowed object is
     *     {@link Build }
     *     
     */
    public void setLastBuild(Build value) {
        this.lastBuild = value;
    }

    /**
     * Gets the value of the lastStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastStatus() {
        return lastStatus;
    }

    /**
     * Sets the value of the lastStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastStatus(String value) {
        this.lastStatus = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the project property.
     * 
     * @return
     *     possible object is
     *     {@link Project }
     *     
     */
    public Project getProject() {
        return project;
    }

    /**
     * Sets the value of the project property.
     * 
     * @param value
     *     allowed object is
     *     {@link Project }
     *     
     */
    public void setProject(Project value) {
        this.project = value;
    }

    /**
     * Gets the value of the projects property.
     * 
     * @return
     *     possible object is
     *     {@link BuildDefinitionProjectsType }
     *     
     */
    public BuildDefinitionProjectsType getProjects() {
        return projects;
    }

    /**
     * Sets the value of the projects property.
     * 
     * @param value
     *     allowed object is
     *     {@link BuildDefinitionProjectsType }
     *     
     */
    public void setProjects(BuildDefinitionProjectsType value) {
        this.projects = value;
    }

    /**
     * Gets the value of the uri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUri() {
        return uri;
    }

    /**
     * Sets the value of the uri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUri(String value) {
        this.uri = value;
    }

}
