//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.07 at 09:26:43 PM EDT 
//


package model.com.rallydev.webservice.v1_34.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Changeset complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Changeset">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rallydev.com/webservice/v1_34/domain}WorkspaceDomainObject">
 *       &lt;sequence>
 *         &lt;element name="Artifacts" type="{http://rallydev.com/webservice/v1_34/domain}ChangesetArtifactsType" minOccurs="0"/>
 *         &lt;element name="Author" type="{http://rallydev.com/webservice/v1_34/domain}User" minOccurs="0"/>
 *         &lt;element name="Builds" type="{http://rallydev.com/webservice/v1_34/domain}ChangesetBuildsType" minOccurs="0"/>
 *         &lt;element name="Changes" type="{http://rallydev.com/webservice/v1_34/domain}ChangesetChangesType" minOccurs="0"/>
 *         &lt;element name="CommitTimestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Revision" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SCMRepository" type="{http://rallydev.com/webservice/v1_34/domain}SCMRepository" minOccurs="0"/>
 *         &lt;element name="Uri" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Changeset", propOrder = {
    "artifacts",
    "author",
    "builds",
    "changes",
    "commitTimestamp",
    "message",
    "name",
    "revision",
    "scmRepository",
    "uri"
})
public class Changeset
    extends WorkspaceDomainObject
{

    @XmlElement(name = "Artifacts")
    protected ChangesetArtifactsType artifacts;
    @XmlElement(name = "Author")
    protected User author;
    @XmlElement(name = "Builds")
    protected ChangesetBuildsType builds;
    @XmlElement(name = "Changes")
    protected ChangesetChangesType changes;
    @XmlElement(name = "CommitTimestamp")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar commitTimestamp;
    @XmlElement(name = "Message")
    protected String message;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "Revision")
    protected String revision;
    @XmlElement(name = "SCMRepository")
    protected SCMRepository scmRepository;
    @XmlElement(name = "Uri")
    protected String uri;

    /**
     * Gets the value of the artifacts property.
     * 
     * @return
     *     possible object is
     *     {@link ChangesetArtifactsType }
     *     
     */
    public ChangesetArtifactsType getArtifacts() {
        return artifacts;
    }

    /**
     * Sets the value of the artifacts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangesetArtifactsType }
     *     
     */
    public void setArtifacts(ChangesetArtifactsType value) {
        this.artifacts = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    public User getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setAuthor(User value) {
        this.author = value;
    }

    /**
     * Gets the value of the builds property.
     * 
     * @return
     *     possible object is
     *     {@link ChangesetBuildsType }
     *     
     */
    public ChangesetBuildsType getBuilds() {
        return builds;
    }

    /**
     * Sets the value of the builds property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangesetBuildsType }
     *     
     */
    public void setBuilds(ChangesetBuildsType value) {
        this.builds = value;
    }

    /**
     * Gets the value of the changes property.
     * 
     * @return
     *     possible object is
     *     {@link ChangesetChangesType }
     *     
     */
    public ChangesetChangesType getChanges() {
        return changes;
    }

    /**
     * Sets the value of the changes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangesetChangesType }
     *     
     */
    public void setChanges(ChangesetChangesType value) {
        this.changes = value;
    }

    /**
     * Gets the value of the commitTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCommitTimestamp() {
        return commitTimestamp;
    }

    /**
     * Sets the value of the commitTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCommitTimestamp(XMLGregorianCalendar value) {
        this.commitTimestamp = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the revision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevision() {
        return revision;
    }

    /**
     * Sets the value of the revision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevision(String value) {
        this.revision = value;
    }

    /**
     * Gets the value of the scmRepository property.
     * 
     * @return
     *     possible object is
     *     {@link SCMRepository }
     *     
     */
    public SCMRepository getSCMRepository() {
        return scmRepository;
    }

    /**
     * Sets the value of the scmRepository property.
     * 
     * @param value
     *     allowed object is
     *     {@link SCMRepository }
     *     
     */
    public void setSCMRepository(SCMRepository value) {
        this.scmRepository = value;
    }

    /**
     * Gets the value of the uri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUri() {
        return uri;
    }

    /**
     * Sets the value of the uri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUri(String value) {
        this.uri = value;
    }

}
