//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.07 at 09:26:43 PM EDT 
//


package model.com.rallydev.webservice.v1_34.domain;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DefectSuite complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DefectSuite">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rallydev.com/webservice/v1_34/domain}Artifact">
 *       &lt;sequence>
 *         &lt;element name="AcceptedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Attachments" type="{http://rallydev.com/webservice/v1_34/domain}DefectSuiteAttachmentsType" minOccurs="0"/>
 *         &lt;element name="Blocked" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Blocker" type="{http://rallydev.com/webservice/v1_34/domain}Blocker" minOccurs="0"/>
 *         &lt;element name="DefectStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Defects" type="{http://rallydev.com/webservice/v1_34/domain}DefectSuiteDefectsType" minOccurs="0"/>
 *         &lt;element name="InProgressDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Iteration" type="{http://rallydev.com/webservice/v1_34/domain}Iteration" minOccurs="0"/>
 *         &lt;element name="Package" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PlanEstimate" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="Rank" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="Release" type="{http://rallydev.com/webservice/v1_34/domain}Release" minOccurs="0"/>
 *         &lt;element name="ScheduleState" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TaskActualTotal" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="TaskEstimateTotal" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="TaskRemainingTotal" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="TaskStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Tasks" type="{http://rallydev.com/webservice/v1_34/domain}DefectSuiteTasksType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DefectSuite", propOrder = {
    "acceptedDate",
    "attachments",
    "blocked",
    "blocker",
    "defectStatus",
    "defects",
    "inProgressDate",
    "iteration",
    "_package",
    "planEstimate",
    "rank",
    "release",
    "scheduleState",
    "taskActualTotal",
    "taskEstimateTotal",
    "taskRemainingTotal",
    "taskStatus",
    "tasks"
})
public class DefectSuite
    extends Artifact
{

    @XmlElement(name = "AcceptedDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar acceptedDate;
    @XmlElement(name = "Attachments")
    protected DefectSuiteAttachmentsType attachments;
    @XmlElement(name = "Blocked")
    protected Boolean blocked;
    @XmlElement(name = "Blocker")
    protected Blocker blocker;
    @XmlElement(name = "DefectStatus")
    protected String defectStatus;
    @XmlElement(name = "Defects")
    protected DefectSuiteDefectsType defects;
    @XmlElement(name = "InProgressDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar inProgressDate;
    @XmlElement(name = "Iteration")
    protected Iteration iteration;
    @XmlElement(name = "Package")
    protected String _package;
    @XmlElement(name = "PlanEstimate")
    protected Double planEstimate;
    @XmlElement(name = "Rank")
    protected BigDecimal rank;
    @XmlElement(name = "Release")
    protected Release release;
    @XmlElement(name = "ScheduleState")
    protected String scheduleState;
    @XmlElement(name = "TaskActualTotal")
    protected Double taskActualTotal;
    @XmlElement(name = "TaskEstimateTotal")
    protected Double taskEstimateTotal;
    @XmlElement(name = "TaskRemainingTotal")
    protected Double taskRemainingTotal;
    @XmlElement(name = "TaskStatus")
    protected String taskStatus;
    @XmlElement(name = "Tasks")
    protected DefectSuiteTasksType tasks;

    /**
     * Gets the value of the acceptedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAcceptedDate() {
        return acceptedDate;
    }

    /**
     * Sets the value of the acceptedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAcceptedDate(XMLGregorianCalendar value) {
        this.acceptedDate = value;
    }

    /**
     * Gets the value of the attachments property.
     * 
     * @return
     *     possible object is
     *     {@link DefectSuiteAttachmentsType }
     *     
     */
    public DefectSuiteAttachmentsType getAttachments() {
        return attachments;
    }

    /**
     * Sets the value of the attachments property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefectSuiteAttachmentsType }
     *     
     */
    public void setAttachments(DefectSuiteAttachmentsType value) {
        this.attachments = value;
    }

    /**
     * Gets the value of the blocked property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBlocked() {
        return blocked;
    }

    /**
     * Sets the value of the blocked property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBlocked(Boolean value) {
        this.blocked = value;
    }

    /**
     * Gets the value of the blocker property.
     * 
     * @return
     *     possible object is
     *     {@link Blocker }
     *     
     */
    public Blocker getBlocker() {
        return blocker;
    }

    /**
     * Sets the value of the blocker property.
     * 
     * @param value
     *     allowed object is
     *     {@link Blocker }
     *     
     */
    public void setBlocker(Blocker value) {
        this.blocker = value;
    }

    /**
     * Gets the value of the defectStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefectStatus() {
        return defectStatus;
    }

    /**
     * Sets the value of the defectStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefectStatus(String value) {
        this.defectStatus = value;
    }

    /**
     * Gets the value of the defects property.
     * 
     * @return
     *     possible object is
     *     {@link DefectSuiteDefectsType }
     *     
     */
    public DefectSuiteDefectsType getDefects() {
        return defects;
    }

    /**
     * Sets the value of the defects property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefectSuiteDefectsType }
     *     
     */
    public void setDefects(DefectSuiteDefectsType value) {
        this.defects = value;
    }

    /**
     * Gets the value of the inProgressDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInProgressDate() {
        return inProgressDate;
    }

    /**
     * Sets the value of the inProgressDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInProgressDate(XMLGregorianCalendar value) {
        this.inProgressDate = value;
    }

    /**
     * Gets the value of the iteration property.
     * 
     * @return
     *     possible object is
     *     {@link Iteration }
     *     
     */
    public Iteration getIteration() {
        return iteration;
    }

    /**
     * Sets the value of the iteration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Iteration }
     *     
     */
    public void setIteration(Iteration value) {
        this.iteration = value;
    }

    /**
     * Gets the value of the package property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackage() {
        return _package;
    }

    /**
     * Sets the value of the package property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackage(String value) {
        this._package = value;
    }

    /**
     * Gets the value of the planEstimate property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPlanEstimate() {
        return planEstimate;
    }

    /**
     * Sets the value of the planEstimate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPlanEstimate(Double value) {
        this.planEstimate = value;
    }

    /**
     * Gets the value of the rank property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRank() {
        return rank;
    }

    /**
     * Sets the value of the rank property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRank(BigDecimal value) {
        this.rank = value;
    }

    /**
     * Gets the value of the release property.
     * 
     * @return
     *     possible object is
     *     {@link Release }
     *     
     */
    public Release getRelease() {
        return release;
    }

    /**
     * Sets the value of the release property.
     * 
     * @param value
     *     allowed object is
     *     {@link Release }
     *     
     */
    public void setRelease(Release value) {
        this.release = value;
    }

    /**
     * Gets the value of the scheduleState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScheduleState() {
        return scheduleState;
    }

    /**
     * Sets the value of the scheduleState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScheduleState(String value) {
        this.scheduleState = value;
    }

    /**
     * Gets the value of the taskActualTotal property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTaskActualTotal() {
        return taskActualTotal;
    }

    /**
     * Sets the value of the taskActualTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTaskActualTotal(Double value) {
        this.taskActualTotal = value;
    }

    /**
     * Gets the value of the taskEstimateTotal property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTaskEstimateTotal() {
        return taskEstimateTotal;
    }

    /**
     * Sets the value of the taskEstimateTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTaskEstimateTotal(Double value) {
        this.taskEstimateTotal = value;
    }

    /**
     * Gets the value of the taskRemainingTotal property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTaskRemainingTotal() {
        return taskRemainingTotal;
    }

    /**
     * Sets the value of the taskRemainingTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTaskRemainingTotal(Double value) {
        this.taskRemainingTotal = value;
    }

    /**
     * Gets the value of the taskStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaskStatus() {
        return taskStatus;
    }

    /**
     * Sets the value of the taskStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaskStatus(String value) {
        this.taskStatus = value;
    }

    /**
     * Gets the value of the tasks property.
     * 
     * @return
     *     possible object is
     *     {@link DefectSuiteTasksType }
     *     
     */
    public DefectSuiteTasksType getTasks() {
        return tasks;
    }

    /**
     * Sets the value of the tasks property.
     * 
     * @param value
     *     allowed object is
     *     {@link DefectSuiteTasksType }
     *     
     */
    public void setTasks(DefectSuiteTasksType value) {
        this.tasks = value;
    }

}
