//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.07 at 09:26:43 PM EDT 
//


package model.com.rallydev.webservice.v1_34.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OperationResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OperationResult">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rallydev.com/webservice/v1_34/domain}WSObject">
 *       &lt;sequence>
 *         &lt;element name="Errors" type="{http://rallydev.com/webservice/v1_34/domain}OperationResultErrorsType" minOccurs="0"/>
 *         &lt;element name="Warnings" type="{http://rallydev.com/webservice/v1_34/domain}OperationResultWarningsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OperationResult", propOrder = {
    "errors",
    "warnings"
})
@XmlSeeAlso({
    QueryResult.class,
    CreateResult.class
})
public class OperationResult
    extends WSObject
{

    @XmlElement(name = "Errors")
    protected OperationResultErrorsType Errors;
    @XmlElement(name = "Warnings")
    protected OperationResultWarningsType Warnings;

    /**
     * Gets the value of the errors property.
     * 
     * @return
     *     possible object is
     *     {@link OperationResultErrorsType }
     *     
     */
    public OperationResultErrorsType getErrors() {
        return Errors;
    }

    /**
     * Sets the value of the errors property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationResultErrorsType }
     *     
     */
    public void setErrors(OperationResultErrorsType value) {
        this.Errors = value;
    }

    /**
     * Gets the value of the warnings property.
     * 
     * @return
     *     possible object is
     *     {@link OperationResultWarningsType }
     *     
     */
    public OperationResultWarningsType getWarnings() {
        return Warnings;
    }

    /**
     * Sets the value of the warnings property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationResultWarningsType }
     *     
     */
    public void setWarnings(OperationResultWarningsType value) {
        this.Warnings = value;
    }

}
