//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.07 at 09:26:43 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://rallydev.com/webservice/v1_34/domain")
package model.com.rallydev.webservice.v1_34.domain;
