//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.07 at 09:26:43 PM EDT 
//


package model.com.rallydev.webservice.v1_34.domain;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PortfolioItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PortfolioItem">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rallydev.com/webservice/v1_34/domain}Artifact">
 *       &lt;sequence>
 *         &lt;element name="AcceptedLeafStoryCount" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="AcceptedLeafStoryPlanEstimateTotal" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="ActualEndDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="ActualStartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Children" type="{http://rallydev.com/webservice/v1_34/domain}PortfolioItemChildrenType" minOccurs="0"/>
 *         &lt;element name="DirectChildrenCount" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="InvestmentCategory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LeafStoryCount" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="LeafStoryPlanEstimateTotal" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="Parent" type="{http://rallydev.com/webservice/v1_34/domain}PortfolioItem" minOccurs="0"/>
 *         &lt;element name="PercentDoneByStoryCount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="PercentDoneByStoryPlanEstimate" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="PlannedEndDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="PlannedStartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="PortfolioItemType" type="{http://rallydev.com/webservice/v1_34/domain}Type" minOccurs="0"/>
 *         &lt;element name="PreliminaryEstimate" type="{http://rallydev.com/webservice/v1_34/domain}PreliminaryEstimate" minOccurs="0"/>
 *         &lt;element name="Rank" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="RiskScore" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="StateChangedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="UnEstimatedLeafStoryCount" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="UserStories" type="{http://rallydev.com/webservice/v1_34/domain}PortfolioItemUserStoriesType" minOccurs="0"/>
 *         &lt;element name="ValueScore" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PortfolioItem", propOrder = {
    "acceptedLeafStoryCount",
    "acceptedLeafStoryPlanEstimateTotal",
    "actualEndDate",
    "actualStartDate",
    "children",
    "directChildrenCount",
    "investmentCategory",
    "leafStoryCount",
    "leafStoryPlanEstimateTotal",
    "parent",
    "percentDoneByStoryCount",
    "percentDoneByStoryPlanEstimate",
    "plannedEndDate",
    "plannedStartDate",
    "portfolioItemType",
    "preliminaryEstimate",
    "rank",
    "riskScore",
    "stateChangedDate",
    "unEstimatedLeafStoryCount",
    "userStories",
    "valueScore"
})
public class PortfolioItem
    extends Artifact
{

    @XmlElement(name = "AcceptedLeafStoryCount")
    protected Long acceptedLeafStoryCount;
    @XmlElement(name = "AcceptedLeafStoryPlanEstimateTotal")
    protected Double acceptedLeafStoryPlanEstimateTotal;
    @XmlElement(name = "ActualEndDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar actualEndDate;
    @XmlElement(name = "ActualStartDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar actualStartDate;
    @XmlElement(name = "Children")
    protected PortfolioItemChildrenType children;
    @XmlElement(name = "DirectChildrenCount")
    protected Long directChildrenCount;
    @XmlElement(name = "InvestmentCategory")
    protected String investmentCategory;
    @XmlElement(name = "LeafStoryCount")
    protected Long leafStoryCount;
    @XmlElement(name = "LeafStoryPlanEstimateTotal")
    protected Double leafStoryPlanEstimateTotal;
    @XmlElement(name = "Parent")
    protected PortfolioItem parent;
    @XmlElement(name = "PercentDoneByStoryCount")
    protected Double percentDoneByStoryCount;
    @XmlElement(name = "PercentDoneByStoryPlanEstimate")
    protected Double percentDoneByStoryPlanEstimate;
    @XmlElement(name = "PlannedEndDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar plannedEndDate;
    @XmlElement(name = "PlannedStartDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar plannedStartDate;
    @XmlElement(name = "PortfolioItemType")
    protected Type portfolioItemType;
    @XmlElement(name = "PreliminaryEstimate")
    protected PreliminaryEstimate preliminaryEstimate;
    @XmlElement(name = "Rank")
    protected BigDecimal rank;
    @XmlElement(name = "RiskScore")
    protected Long riskScore;
    @XmlElement(name = "StateChangedDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar stateChangedDate;
    @XmlElement(name = "UnEstimatedLeafStoryCount")
    protected Long unEstimatedLeafStoryCount;
    @XmlElement(name = "UserStories")
    protected PortfolioItemUserStoriesType userStories;
    @XmlElement(name = "ValueScore")
    protected Long valueScore;

    /**
     * Gets the value of the acceptedLeafStoryCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAcceptedLeafStoryCount() {
        return acceptedLeafStoryCount;
    }

    /**
     * Sets the value of the acceptedLeafStoryCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAcceptedLeafStoryCount(Long value) {
        this.acceptedLeafStoryCount = value;
    }

    /**
     * Gets the value of the acceptedLeafStoryPlanEstimateTotal property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAcceptedLeafStoryPlanEstimateTotal() {
        return acceptedLeafStoryPlanEstimateTotal;
    }

    /**
     * Sets the value of the acceptedLeafStoryPlanEstimateTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAcceptedLeafStoryPlanEstimateTotal(Double value) {
        this.acceptedLeafStoryPlanEstimateTotal = value;
    }

    /**
     * Gets the value of the actualEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getActualEndDate() {
        return actualEndDate;
    }

    /**
     * Sets the value of the actualEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setActualEndDate(XMLGregorianCalendar value) {
        this.actualEndDate = value;
    }

    /**
     * Gets the value of the actualStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getActualStartDate() {
        return actualStartDate;
    }

    /**
     * Sets the value of the actualStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setActualStartDate(XMLGregorianCalendar value) {
        this.actualStartDate = value;
    }

    /**
     * Gets the value of the children property.
     * 
     * @return
     *     possible object is
     *     {@link PortfolioItemChildrenType }
     *     
     */
    public PortfolioItemChildrenType getChildren() {
        return children;
    }

    /**
     * Sets the value of the children property.
     * 
     * @param value
     *     allowed object is
     *     {@link PortfolioItemChildrenType }
     *     
     */
    public void setChildren(PortfolioItemChildrenType value) {
        this.children = value;
    }

    /**
     * Gets the value of the directChildrenCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDirectChildrenCount() {
        return directChildrenCount;
    }

    /**
     * Sets the value of the directChildrenCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDirectChildrenCount(Long value) {
        this.directChildrenCount = value;
    }

    /**
     * Gets the value of the investmentCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvestmentCategory() {
        return investmentCategory;
    }

    /**
     * Sets the value of the investmentCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvestmentCategory(String value) {
        this.investmentCategory = value;
    }

    /**
     * Gets the value of the leafStoryCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLeafStoryCount() {
        return leafStoryCount;
    }

    /**
     * Sets the value of the leafStoryCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLeafStoryCount(Long value) {
        this.leafStoryCount = value;
    }

    /**
     * Gets the value of the leafStoryPlanEstimateTotal property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getLeafStoryPlanEstimateTotal() {
        return leafStoryPlanEstimateTotal;
    }

    /**
     * Sets the value of the leafStoryPlanEstimateTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLeafStoryPlanEstimateTotal(Double value) {
        this.leafStoryPlanEstimateTotal = value;
    }

    /**
     * Gets the value of the parent property.
     * 
     * @return
     *     possible object is
     *     {@link PortfolioItem }
     *     
     */
    public PortfolioItem getParent() {
        return parent;
    }

    /**
     * Sets the value of the parent property.
     * 
     * @param value
     *     allowed object is
     *     {@link PortfolioItem }
     *     
     */
    public void setParent(PortfolioItem value) {
        this.parent = value;
    }

    /**
     * Gets the value of the percentDoneByStoryCount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPercentDoneByStoryCount() {
        return percentDoneByStoryCount;
    }

    /**
     * Sets the value of the percentDoneByStoryCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPercentDoneByStoryCount(Double value) {
        this.percentDoneByStoryCount = value;
    }

    /**
     * Gets the value of the percentDoneByStoryPlanEstimate property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPercentDoneByStoryPlanEstimate() {
        return percentDoneByStoryPlanEstimate;
    }

    /**
     * Sets the value of the percentDoneByStoryPlanEstimate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPercentDoneByStoryPlanEstimate(Double value) {
        this.percentDoneByStoryPlanEstimate = value;
    }

    /**
     * Gets the value of the plannedEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPlannedEndDate() {
        return plannedEndDate;
    }

    /**
     * Sets the value of the plannedEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPlannedEndDate(XMLGregorianCalendar value) {
        this.plannedEndDate = value;
    }

    /**
     * Gets the value of the plannedStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPlannedStartDate() {
        return plannedStartDate;
    }

    /**
     * Sets the value of the plannedStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPlannedStartDate(XMLGregorianCalendar value) {
        this.plannedStartDate = value;
    }

    /**
     * Gets the value of the portfolioItemType property.
     * 
     * @return
     *     possible object is
     *     {@link Type }
     *     
     */
    public Type getPortfolioItemType() {
        return portfolioItemType;
    }

    /**
     * Sets the value of the portfolioItemType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Type }
     *     
     */
    public void setPortfolioItemType(Type value) {
        this.portfolioItemType = value;
    }

    /**
     * Gets the value of the preliminaryEstimate property.
     * 
     * @return
     *     possible object is
     *     {@link PreliminaryEstimate }
     *     
     */
    public PreliminaryEstimate getPreliminaryEstimate() {
        return preliminaryEstimate;
    }

    /**
     * Sets the value of the preliminaryEstimate property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreliminaryEstimate }
     *     
     */
    public void setPreliminaryEstimate(PreliminaryEstimate value) {
        this.preliminaryEstimate = value;
    }

    /**
     * Gets the value of the rank property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRank() {
        return rank;
    }

    /**
     * Sets the value of the rank property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRank(BigDecimal value) {
        this.rank = value;
    }

    /**
     * Gets the value of the riskScore property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRiskScore() {
        return riskScore;
    }

    /**
     * Sets the value of the riskScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRiskScore(Long value) {
        this.riskScore = value;
    }

    /**
     * Gets the value of the stateChangedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStateChangedDate() {
        return stateChangedDate;
    }

    /**
     * Sets the value of the stateChangedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStateChangedDate(XMLGregorianCalendar value) {
        this.stateChangedDate = value;
    }

    /**
     * Gets the value of the unEstimatedLeafStoryCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getUnEstimatedLeafStoryCount() {
        return unEstimatedLeafStoryCount;
    }

    /**
     * Sets the value of the unEstimatedLeafStoryCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setUnEstimatedLeafStoryCount(Long value) {
        this.unEstimatedLeafStoryCount = value;
    }

    /**
     * Gets the value of the userStories property.
     * 
     * @return
     *     possible object is
     *     {@link PortfolioItemUserStoriesType }
     *     
     */
    public PortfolioItemUserStoriesType getUserStories() {
        return userStories;
    }

    /**
     * Sets the value of the userStories property.
     * 
     * @param value
     *     allowed object is
     *     {@link PortfolioItemUserStoriesType }
     *     
     */
    public void setUserStories(PortfolioItemUserStoriesType value) {
        this.userStories = value;
    }

    /**
     * Gets the value of the valueScore property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getValueScore() {
        return valueScore;
    }

    /**
     * Sets the value of the valueScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setValueScore(Long value) {
        this.valueScore = value;
    }

}
