//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.07 at 09:26:43 PM EDT 
//


package model.com.rallydev.webservice.v1_34.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Project complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Project">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rallydev.com/webservice/v1_34/domain}WorkspaceDomainObject">
 *       &lt;sequence>
 *         &lt;element name="BuildDefinitions" type="{http://rallydev.com/webservice/v1_34/domain}ProjectBuildDefinitionsType" minOccurs="0"/>
 *         &lt;element name="Children" type="{http://rallydev.com/webservice/v1_34/domain}ProjectChildrenType" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Iterations" type="{http://rallydev.com/webservice/v1_34/domain}ProjectIterationsType" minOccurs="0"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Notes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Owner" type="{http://rallydev.com/webservice/v1_34/domain}User" minOccurs="0"/>
 *         &lt;element name="Parent" type="{http://rallydev.com/webservice/v1_34/domain}Project" minOccurs="0"/>
 *         &lt;element name="Releases" type="{http://rallydev.com/webservice/v1_34/domain}ProjectReleasesType" minOccurs="0"/>
 *         &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TeamMembers" type="{http://rallydev.com/webservice/v1_34/domain}ProjectTeamMembersType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Project", propOrder = {
    "buildDefinitions",
    "children",
    "description",
    "iterations",
    "name",
    "notes",
    "owner",
    "parent",
    "releases",
    "state",
    "teamMembers"
})
public class Project
    extends WorkspaceDomainObject
{

    @XmlElement(name = "BuildDefinitions")
    protected ProjectBuildDefinitionsType buildDefinitions;
    @XmlElement(name = "Children")
    protected ProjectChildrenType children;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "Iterations")
    protected ProjectIterationsType iterations;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "Notes")
    protected String notes;
    @XmlElement(name = "Owner")
    protected User owner;
    @XmlElement(name = "Parent")
    protected Project parent;
    @XmlElement(name = "Releases")
    protected ProjectReleasesType releases;
    @XmlElement(name = "State")
    protected String state;
    @XmlElement(name = "TeamMembers")
    protected ProjectTeamMembersType teamMembers;

    /**
     * Gets the value of the buildDefinitions property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectBuildDefinitionsType }
     *     
     */
    public ProjectBuildDefinitionsType getBuildDefinitions() {
        return buildDefinitions;
    }

    /**
     * Sets the value of the buildDefinitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectBuildDefinitionsType }
     *     
     */
    public void setBuildDefinitions(ProjectBuildDefinitionsType value) {
        this.buildDefinitions = value;
    }

    /**
     * Gets the value of the children property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectChildrenType }
     *     
     */
    public ProjectChildrenType getChildren() {
        return children;
    }

    /**
     * Sets the value of the children property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectChildrenType }
     *     
     */
    public void setChildren(ProjectChildrenType value) {
        this.children = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the iterations property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectIterationsType }
     *     
     */
    public ProjectIterationsType getIterations() {
        return iterations;
    }

    /**
     * Sets the value of the iterations property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectIterationsType }
     *     
     */
    public void setIterations(ProjectIterationsType value) {
        this.iterations = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    public User getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setOwner(User value) {
        this.owner = value;
    }

    /**
     * Gets the value of the parent property.
     * 
     * @return
     *     possible object is
     *     {@link Project }
     *     
     */
    public Project getParent() {
        return parent;
    }

    /**
     * Sets the value of the parent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Project }
     *     
     */
    public void setParent(Project value) {
        this.parent = value;
    }

    /**
     * Gets the value of the releases property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectReleasesType }
     *     
     */
    public ProjectReleasesType getReleases() {
        return releases;
    }

    /**
     * Sets the value of the releases property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectReleasesType }
     *     
     */
    public void setReleases(ProjectReleasesType value) {
        this.releases = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the teamMembers property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectTeamMembersType }
     *     
     */
    public ProjectTeamMembersType getTeamMembers() {
        return teamMembers;
    }

    /**
     * Sets the value of the teamMembers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectTeamMembersType }
     *     
     */
    public void setTeamMembers(ProjectTeamMembersType value) {
        this.teamMembers = value;
    }

}
