//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.07 at 09:26:43 PM EDT 
//


package model.com.rallydev.webservice.v1_34.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TestCase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TestCase">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rallydev.com/webservice/v1_34/domain}Artifact">
 *       &lt;sequence>
 *         &lt;element name="Attachments" type="{http://rallydev.com/webservice/v1_34/domain}TestCaseAttachmentsType" minOccurs="0"/>
 *         &lt;element name="DefectStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LastBuild" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LastRun" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="LastVerdict" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Method" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Objective" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Package" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PostConditions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PreConditions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Priority" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Recycled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Results" type="{http://rallydev.com/webservice/v1_34/domain}TestCaseResultsType" minOccurs="0"/>
 *         &lt;element name="Risk" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Steps" type="{http://rallydev.com/webservice/v1_34/domain}TestCaseStepsType" minOccurs="0"/>
 *         &lt;element name="TestFolder" type="{http://rallydev.com/webservice/v1_34/domain}TestFolder" minOccurs="0"/>
 *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ValidationExpectedResult" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ValidationInput" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="WorkProduct" type="{http://rallydev.com/webservice/v1_34/domain}Artifact" minOccurs="0"/>
 *         &lt;element name="AutomatedScriptLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Issue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StepName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TestCaseActual" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="TestCaseEstimate" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="TestCaseToDo" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TestCase", propOrder = {
    "rest"
})
public class TestCase
    extends Artifact
{

    @XmlElementRefs({
        @XmlElementRef(name = "Objective", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "PostConditions", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Priority", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Type", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "LastRun", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "AutomatedScriptLocation", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Recycled", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "DefectStatus", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "TestFolder", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Attachments", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Method", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "PreConditions", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "LastBuild", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "StepName", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Issue", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "WorkProduct", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Package", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Steps", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "TestCaseEstimate", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "TestCaseToDo", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ValidationInput", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "TestCaseActual", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ValidationExpectedResult", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Results", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Risk", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "LastVerdict", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> rest;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "Type" is used by two different parts of a schema. See: 
     * line 894 of file:/C:/Users/Tash/Desktop/rally.xsd
     * line 8 of file:/C:/Users/Tash/Desktop/rally.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the rest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link TestFolder }{@code >}
     * {@link JAXBElement }{@code <}{@link TestCaseAttachmentsType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Artifact }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link TestCaseStepsType }{@code >}
     * {@link JAXBElement }{@code <}{@link Double }{@code >}
     * {@link JAXBElement }{@code <}{@link Double }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Double }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link TestCaseResultsType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getRest() {
        if (rest == null) {
            rest = new ArrayList<JAXBElement<?>>();
        }
        return this.rest;
    }

}
