//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.07 at 09:26:43 PM EDT 
//


package model.com.rallydev.webservice.v1_34.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WorkspacePermission complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WorkspacePermission">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rallydev.com/webservice/v1_34/domain}UserPermission">
 *       &lt;sequence>
 *         &lt;element name="Workspace" type="{http://rallydev.com/webservice/v1_34/domain}Workspace" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WorkspacePermission", propOrder = {
    "workspace"
})
public class WorkspacePermission
    extends UserPermission
{

    @XmlElement(name = "Workspace")
    protected Workspace workspace;

    /**
     * Gets the value of the workspace property.
     * 
     * @return
     *     possible object is
     *     {@link Workspace }
     *     
     */
    public Workspace getWorkspace() {
        return workspace;
    }

    /**
     * Sets the value of the workspace property.
     * 
     * @param value
     *     allowed object is
     *     {@link Workspace }
     *     
     */
    public void setWorkspace(Workspace value) {
        this.workspace = value;
    }

}
