//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.07 at 09:26:43 PM EDT 
//


package model.com.rallydev.webservice.v1_34.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WorkspaceDomainObject complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WorkspaceDomainObject">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rallydev.com/webservice/v1_34/domain}DomainObject">
 *       &lt;sequence>
 *         &lt;element name="Workspace" type="{http://rallydev.com/webservice/v1_34/domain}Workspace" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WorkspaceDomainObject", propOrder = {
    "workspace"
})
@XmlSeeAlso({
    Attachment.class,
    RevisionHistory.class,
    TestCaseStep.class,
    BuildMetric.class,
    AttachmentContent.class,
    Project.class,
    ConversationPost.class,
    PreliminaryEstimate.class,
    ArtifactNotification.class,
    TestFolder.class,
    Iteration.class,
    TestCaseResult.class,
    Build.class,
    Tag.class,
    Program.class,
    AttributeDefinition.class,
    WorkspaceConfiguration.class,
    Change.class,
    BuildDefinition.class,
    Release.class,
    TimeEntryItem.class,
    SCMRepository.class,
    Type.class,
    TypeDefinition.class,
    Changeset.class,
    CumulativeFlowData.class,
    BuildMetricDefinition.class,
    Artifact.class,
    Revision.class,
    TimeEntryValue.class,
    UserIterationCapacity.class
})
public class WorkspaceDomainObject
    extends DomainObject
{

    @XmlElement(name = "Workspace")
    protected Workspace workspace;

    /**
     * Gets the value of the workspace property.
     * 
     * @return
     *     possible object is
     *     {@link Workspace }
     *     
     */
    public Workspace getWorkspace() {
        return workspace;
    }

    /**
     * Sets the value of the workspace property.
     * 
     * @param value
     *     allowed object is
     *     {@link Workspace }
     *     
     */
    public void setWorkspace(Workspace value) {
        this.workspace = value;
    }

}
