//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.07 at 09:26:43 PM EDT 
//


package model.com.rallydev.webservice.v1_34.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WSObject complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WSObject">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ref" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="objectVersion" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="refObjectName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="rallyAPIMajor" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="rallyAPIMinor" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WSObject")
@XmlSeeAlso({
    OperationResult.class,
    PersistableObject.class
})
public class WSObject {

    @XmlAttribute(name = "ref")
    protected String ref;
    @XmlAttribute(name = "objectVersion")
    protected Long objectVersion;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "refObjectName")
    protected String refObjectName;
    @XmlAttribute(name = "_rallyAPIMajor")
    protected Long _rallyAPIMajor;
    @XmlAttribute(name = "rallyAPIMinor")
    protected Long _rallyAPIMinor;

    /**
     * Gets the value of the ref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRef() {
        return ref;
    }

    /**
     * Sets the value of the ref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRef(String value) {
        this.ref = value;
    }

    /**
     * Gets the value of the objectVersion property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getObjectVersion() {
        return objectVersion;
    }

    /**
     * Sets the value of the objectVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setObjectVersion(Long value) {
        this.objectVersion = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the refObjectName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefObjectName() {
        return refObjectName;
    }

    /**
     * Sets the value of the refObjectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefObjectName(String value) {
        this.refObjectName = value;
    }

    /**
     * Gets the value of the rallyAPIMajor property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long get_rallyAPIMajor() {
        return _rallyAPIMajor;
    }

    /**
     * Sets the value of the rallyAPIMajor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void set_rallyAPIMajor(Long value) {
        this._rallyAPIMajor = value;
    }

    /**
     * Gets the value of the rallyAPIMinor property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRallyAPIMinor() {
        return _rallyAPIMinor;
    }

    /**
     * Sets the value of the rallyAPIMinor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRallyAPIMinor(Long value) {
        this._rallyAPIMinor = value;
    }

}
